### ISSUE TITLE
AsyncDeduped.swift is missing

### ISSUE THREAD

**Issue by kukushi** [staminajim/FileSinki#3]
<img width="272" alt="image" src="https://github.com/staminajim/FileSinki/assets/2424654/b9a024be-a7a3-43af-aebf-d10208814b6c">

**Comment by staminajim** [comment]
Hi thanks for reporting that! That file was removed, but my projects using Filesinki as a dependency didn't seem to care that the standalone project was still pointing to it.

Fixed
